services:

  appointment-manager-db:
    image: postgres:17.5-alpine
    container_name: appointment-manager-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - appointment-manager-db-data:/var/lib/postgresql/data
      - ./backend/src/db/init:/docker-entrypoint-initdb.d
    networks:
      - appointment-manager_backend-db_network

  appointment-manager-backend:
    container_name: appointment-manager-backend
    build:
      context:  ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /backend/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - appointment-manager-db
    networks:
      - appointment-manager_backend-db_network


volumes:
  appointment-manager-db-data:

networks:
  appointment-manager_backend-db_network:
    driver: bridge
